cues:
  audio:
    type: raw
    guaranteed: true
    scope: speaker
    policy:
      type: random
      key: spk_id
      resource: /data/tse_cue_project/manifests/librimix_basic_clean/train-100/cues/audio.json
